server:
  port: 8762

eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://root:root@peer1:8761/eureka/

spring:
  application:
    name: eurekaserver-b

security:
  basic:
    enabled: true
  user:
    name: root
    password: root
