server:
  port: 8766

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://root:root@127.0.0.1:8761/eureka/,http://root:root@127.0.0.1:8762/eureka/

spring:
  application:
    name: consumer-feign-a

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
feign:
  hystrix:
    enabled: true

